add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/Clk_S
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/Rst_N
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/AHBSlave121_In
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/Clk_AHB
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/Reset_AHB
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/AHBSlave121_Out
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/AHBSlave123_In
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/AHBSlave123_Out
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/AHBMaster123_In
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/AHBMaster123_Out
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/DataIn_shyloc
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/DataIn_NewValid
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/DataOut
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/DataOut_NewValid
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/Ready_Ext
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/ForceStop
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/AwaitingConfig
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/Ready
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/FIFO_Full
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/EOP
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/Finished
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_HR/Error