add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/Clk_S
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/Rst_N
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/AHBSlave121_In
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/Clk_AHB
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/Reset_AHB
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/AHBSlave121_Out
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/DataIn
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/DataIn_NewValid
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/IsHeaderIn
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/NbitsIn
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/DataOut
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/DataOut_NewValid
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/ForceStop
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/Ready_Ext
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/AwaitingConfig
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/Ready
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/FIFO_Full
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/EOP
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/Finished
add wave -position end  sim:/shyloc_ahb_system_tb/DUT/compressor_H/Error