vcom -work work -2008 -quiet $DUT/SpW_router/rmap_target.vhd
vcom -work work -2008 -quiet $DUT/SpW_router/rmap_target_full.vhd
vcom -work work -2008 -quiet $DUT/SpW_router/single_port_single_clock_ram.vhd
vcom -work work -2008 -quiet $DUT/SpW_router/rmap_crc_calculator.vhd
vcom -work work -2008 -quiet $DUT/SpW_router/rmap_crc_checker.vhd
vcom -work work -2008 -quiet $DUT/SpW_router/rmap_command_controller.vhd
vcom -work work -2008 -quiet $DUT/SpW_router/rmap_command_controller_parallel_interface.vhd
vcom -work work -2008 -quiet $DUT/SpW_router/rmap_spw_wrap.vhd
vcom -work work -2008 -quiet $DUT/SpW_router/rmap_reply_controller.vhd
vcom -work work -2008 -quiet $DUT/SpW_router/rmap_reply_controller_parallel_interface.vhd
vcom -work work -2008 -quiet $DUT/SpW_router/rmap_initiator.vhd
vcom -work work -2008 -quiet $DUT/SpW_router/rmap_initiator_top_level.vhd